to_vegan_list = {
    "chicken bouillon": "vegetable bouillon",
    "beef bouillon": "vegetable bouillon",
    "pork bouillon""vegetable bouillon",
    "chicken broth": "vegetable broth",
    "beef broth": "vegetable broth",
    "chicken stock": "vegetable broth",
    "beef stock": "vegetable broth",
    "pork stock": "vegetable broth",
    "meat": "tofu",
    "beef": "tempeh",
    "veal": "tofu",
    "lamb": "tempeh",
    "bacon": "vegan bacon",
    "steak": "seitan steak",
    "turkey": "tofurky",
    "pepperoni": "tofurky deli slice",
    "pastrami": "tofurky deli slice",
    "salami": "tofurky deli slice",
    "ribs": "seitan ribs",
    "ground meat": "textured soy protein",
    "ground beef": "textured soy protein",
    "ground pork": "textured soy protein",
    "filet mignon": "portobello mushroom",
    "rib-eye": "portobello mushroom",
    "burger": "veggie burger",
    "meatball": "veggie meatball",
    "sausage": "veggie sausage",
    "chicken breast": "seitan tenders",
    "chicken thigh": "seitan tenders",
    "chicken leg": "seitan tenders",
    "chicken nuggets": "seitan nuggets",
    "pork": "tempeh",
    "jerky": "veggie jerky",
    "tuna": "tempeh",
    "tilapia": "tempeh",
    "sardine": "tempeh",
    "salmon": "tempeh",
    "squid": "tempeh",
    "cod": "tempeh",
    "clam": "tempeh",
    "halibut": "tempeh",
    "anchovy": "tempeh",
    "anchovie": "tempeh",
    "calamari": "tempeh",
    "shrimp": "tofu",
    "prawn": "tofu",
    "milk": "soy milk",
    "milk powder": "almond milk powder",
    "ice cream": "soy ice cream",
    "mozzarella cheese": "vegan mozzarella cheese",
    "mozzarella": "vegan mozzarella",
    "parmesan cheese": "vegan parmesan cheese",
    "cheese": "crumbled tofu",
    "butter": "vegan margarine",
    "yogurt", "almond milk yogurt",
    "scrambled egg": "tofu scramble",
    "egg yolk": "tofu",
    "egg": "tofu",
    "yolk", "tofu",
    "instant pudding": "dairy free instant pudding",
    "pudding": "dairy free pudding",
    "sour cream": "vegan sour cream",
    "mayonnaise": "vegan mayonnaise",
    "ketchup": "vegan ketchup",
    "gelatin": "agar flakes",
    "honey", "agave nectar",
    "chocolate": "non-dairy chocolate",
    "hollandaise sauce": "vegan hollandaise sauce",
    "oyster sauce": "vegetarian oyster sauce",
    "worcestershire sauce": "organic worcestershire sauce",
    "bread": "wheat tortilla",
    "bread toasts": "wheat tortilla",
    "bagel": "vegan bagel",
    "pancake", "vegan pancake"
}
