healthy = {
    "whole milk": "low-fat milk",
    "ice cream": "low-fat frozen yoghurt",
    "whipping cream": "imitation whipped cream(made with skimmed milk)",
    "whipped cream": "imitation whipped cream(made with skimmed milk)",
    "sour cream": "plain low-fat yoghurt",
    "cream cheese": "fat-free cream cheese",
    "american cheese": "fat-free cheese",
    "cottage cheese": "low-fat cottage cheese",
    "mozzarella cheese": "part-skim milk mozzarella cheese",
    "ricotta cheese": "part-skim milk ricotta cheese",
    "granola": "oatmeal",
    "coffee cream": "low-fat milk",
    "ramen noodles": "rice",
    "flour": "almond flour",
    "bologna": "low-fat bologna",
    "sausage": "lean ham",
    "vegetable oil": "coconut oil",
    "tortillas": "lettuce leaves",
    "tortilla": "lettuce leaves",
    "couscous": "cauliflower rice",
    "rice": "cauliflower rice",
    "sugar": "stevia",
    "pasta sauce": "almond pesto",
    "penne": "whole wheat penne",
    "linguine": "whole wheat linguine",
    "fettuccine": "whole wheat fettuccine",
    "spaghetti": "spaghetti squash",
    "lasagna": "vegetable lasagna",
    "macaroni": "cauliflower",
    "mac and cheese": "cauliflower and cheese",
    "pasta salad": "mixed vegetables",
    "pasta": "veggie noodles",
    "breadcrumbs": "pork rinds",
    "bread crumbs": "pork rinds",
    "sliced bread": "eggplant",
    "white bread": "whole wheat bread",
    "pancakes": "oatmeal pancakes",
    "pizza crust": "fathead crust",
    "milk": "almond milk",
    "taco shell": "lettuce wrap",
    "french fries": "butternut squash fries",
    "hamburger buns": "portabello mushrooms",
    "burger buns": "portabello mushrooms",
    "buns": "portabello mushrooms",
    "scalloped potatoes": "tempeh",
    "mashed potatoes": "mashed cauliflower",
    "sweet potatoes": "zucchini",
    "potatoes": "zucchini",
    "potato chips": "kale chips",
    "hash browns": "squash",
    "bacon": "fresh pork belly",
    "baking soda": "sodium-free baking soda",
    "barbecue sauce": "low-sodium ketchup",
    "bbq sauce": "low-sodium ketchup",
    "beef jerky": "beef strips",
    "beef noodle soup": "mushroom broth",
    "blue cheese": "part-skim milk mozzarella cheese",
    "bullion": "mushroom broth",
    "camembert cheese": "part-skim milk mozzarella cheese",
    "canned anchovy": "low-sodium sardines",
    "canned corn": "fresh corn",
    "canned tomatoes": "fresh tomatoes",
    "capocollo": "low-sodium ham",
    "chicken noodle soup": "mushroom broth",
    "chicken soup": "mushroom broth",
    "cream of vegetable soup": "mushroom broth",
    "dried beef": "beef strips",
    "feta cheese": "part-skim milk mozzarella cheese",
    "fish sauce": "vinegar",
    "gouda cheese": "part-skim milk mozzarella cheese",
    "hot pepper sauce": "red pepper flakes",
    "instant soup": "mushroom broth",
    "italian salami": "low-sodium ham",
    "ketchup": "low-sodium ketchup",
    "marinade": "flavored vinegar",
    "mayonnaise": "yogurt",
    "mortadella": "low-sodium ham",
    "ground beef": "extra-lean ground beef",
    "olives": "baked grapes",
    "onion soup": "mushroom broth",
    "oyster sauce": "vinegar",
    "paremsan cheese": "part-skim milk mozzarella cheese",
    "pepperoni": "low-sodium ham",
    "pickle": "cucumber",
    "pickled eggplant": "eggplant",
    "pickled peppers": "fresh chiles",
    "prosciutto": "low-sodium ham",
    "queso seco": "part-skim milk mozzarella cheese",
    "ranch dressing": "balsamic vinegar",
    "relish": "low-sodium sweet relish",
    "romano cheese": "part-skim milk mozzarella cheese",
    "roquefort cheese": "part-skim milk mozzarella cheese",
    "salad dressing": "olive oil",
    "salami": "low-sodium ham",
    "salt and pepper": "pepper",
    "salt cod": "fresh cod",
    "salted butter": "unsalted butter",
    "salted mackerel": "fresh mackerel",
    "lightly salted ": "",
    "salted ": "",
    "sauerkraut": "chopped cabbage",
    "sea salt": "sesame oil",
    "salt": "low-sodium salt substitute",
    "smoked herring": "seared herring",
    "smoked salmon": "fresh salmon",
    "smoked white fish": "seared white fish",
    "soup cube": "mushroom broth",
    "soup": "vegetable puree",
    "soy sauce": "low-sodium soy sauce",
    "steak sauce": "low-sodium steak sauce",
    "stock cube": "mushroom broth",
    "stock": "mushroom broth",
    "table salt": "sesame oil",
    "teriyaki sauce": "vinegar",
    "tomato soup": "mushroom broth",
    "turkey bacon": "fresh turkey strips",
    "turkey salami": "low-sodium ham",
    "vegetable soup": "mushroom broth",
    "chocolate": "carob",
    "beef": "beef(trimmed of external fat)",
    "pork": "lean smoked ham",
    "breaded fish": "unbreaded shellfish",
    "fried fish": "unbreaded shellfish",
    "whole eggs": "egg whites",
    "eggs": "egg whites",
    "egg": "egg whites",
    "whole egg": "egg whites",
    "chorizo sausage": "turkey sausage",
    "croissants": "hard french rolls",
    "brioches": "hard french rolls",
    "butter": "whipped butter",
    "avocado": "cucumber slices",
    "margarine": "diet margarine",
    "cheddar cheese": "fat-free cheese",
    "cheese": "low-fat cheese"
}

inv_map = {v: k for k, v in healthy.items()}
print(inv_map)
