healthy = {
    "flour": "almond flour",
    "vegetable oil": "coconut oil",
    "tortillas": "lettuce leaves",
    "tortilla": "lettuce leaves",
    "couscous": "cauliflower rice",
    "rice": "cauliflower rice",
    "sugar": "stevia",
    "pasta sauce": "almond pesto",
    "penne": "whole wheat penne",
    "linguine": "whole wheat linguine",
    "fettuccine": "whole wheat fettuccine",
    "spaghetti": "spaghetti squash",
    "lasagna": "vegetable lasagna",
    "macaroni": "cauliflower",
    "mac and cheese": "cauliflower and cheese",
    "pasta salad": "mixed vegetables",
    "pasta": "veggie noodles",
    "breadcrumbs": "pork rinds",
    "bread crumbs": "pork rinds",
    "sliced bread": "eggplant",
    "white bread": "whole wheat bread",
    "pancakes": "oatmeal pancakes",
    "pizza crust": "fathead crust",
    "milk": "almond milk",
    "taco shell": "lettuce wrap",
    "french fries": "butternut squash fries",
    "hamburger buns": "portabello mushrooms",
    "burger buns": "portabello mushrooms",
    "buns": "portabello mushrooms",
    "scalloped potatoes": "tempeh",
    "mashed potatoes": "mashed cauliflower",
    "sweet potatoes": "zucchini",
    "potatoes": "zucchini",
    "potato chips": "kale chips",
    "hash browns": "squash",
    "bacon": "fresh pork belly",
    "baking soda": "sodium-free baking soda",
    "barbecue sauce": "low-sodium ketchup",
    "bbq sauce": "low-sodium ketchup",
    "beef jerky": "beef strips",
    "beef noodle soup": "mushroom broth",
    "blue cheese": "mozzarella cheese",
    "bullion": "mushroom broth",
    "camembert cheese": "mozzarella cheese",
    "canned anchovy": "low-sodium sardines",
    "canned corn": "fresh corn",
    "canned tomatoes": "fresh tomatoes",
    "capocollo": "low-sodium ham",
    "chicken noodle soup": "mushroom broth",
    "chicken soup": "mushroom broth",
    "cream of vegetable soup": "mushroom broth",
    "dried beef": "beef strips",
    "feta cheese": "mozzarella cheese",
    "fish sauce": "vinegar",
    "gouda cheese": "mozzarella cheese",
    "hot pepper sauce": "red pepper flakes",
    "instant soup": "mushroom broth",
    "italian salami": "low-sodium ham",
    "ketchup": "low-sodium ketchup",
    "marinade": "flavored vinegar",
    "mayonnaise": "yogurt",
    "mortadella": "low-sodium ham",
    "olives": "baked grapes",
    "onion soup": "mushroom broth",
    "oyster sauce": "vinegar",
    "paremsan cheese": "mozzarella cheese",
    "pepperoni": "low-sodium ham",
    "pickle": "cucumber",
    "pickled eggplant": "eggplant",
    "pickled peppers": "fresh chiles",
    "prosciutto": "low-sodium ham",
    "queso seco": "mozzarella cheese",
    "ranch dressing": "balsamic vinegar",
    "relish": "low-sodium sweet relish",
    "romano cheese": "mozzarella cheese",
    "roquefort cheese": "mozzarella cheese",
    "salad dressing": "olive oil",
    "salami": "low-sodium ham",
    "salt and pepper": "pepper",
    "salt cod": "fresh cod",
    "salted butter": "unsalted butter",
    "salted mackerel": "fresh mackerel",
    "lightly salted ": "",
    "salted ": "",
    "sauerkraut": "chopped cabbage",
    "sea salt": "sesame oil",
    "salt": "low-sodium salt substitute",
    "smoked herring": "seared herring",
    "smoked salmon": "fresh salmon",
    "smoked white fish": "seared white fish",
    "soup cube": "mushroom broth",
    "soup": "vegetable puree",
    "soy sauce": "low-sodium soy sauce",
    "steak sauce": "low-sodium steak sauce",
    "stock cube": "mushroom broth",
    "stock": "mushroom broth",
    "table salt": "sesame oil",
    "teriyaki sauce": "vinegar",
    "tomato soup": "mushroom broth",
    "turkey bacon": "fresh turkey strips",
    "turkey salami": "low-sodium ham",
    "vegetable soup": "mushroom broth",
    "chocolate": "carob"
}

vegetarian = {
    "chicken bouillon": "vegetable bouillon",
    "beef bouillon": "vegetable bouillon",
    "pork bouillon": "vegetable bouillon",
    "chicken broth": "vegetable broth",
    "chicken stock": "vegetable broth",
    "beef stock": "vegetable broth",
    "beef broth": "vegetable broth",
    "pork stock": "vegetable broth",
    "clam juice": "vegetable broth",
    "fish juice": "vegetable broth",
    "oyster juice": "vegetable broth",
    "ground meat": "textured soy protein",
    "ground beef": "textured soy protein",
    "ground pork": "textured soy protein",
    "pepperoni": "veggie deli slice",
    "pastrami": "veggie deli slice",
    "salami": "veggie deli slice",
    "steak": "portobello mushroom",
    "filet mignon": "portobello mushroom",
    "rib-eye": "portobello mushroom",
    "ribs": "portobello mushroom",
    "burger": "veggie burger",
    "meatball": "veggie meatball",
    "sausage": "veggie sausage",
    "bacon": "veggie bacon",
    "turkey": "soy turkey patties",
    "chicken breast": "seitan tenders",
    "chicken leg": "seitan tenders",
    "chicken thigh": "seitan tenders",
    "chicken": "soy chicken patties",
    "chicken nuggets": "soy chicken nuggets",
    "jerky": "veggie jerky",
    "pork": "tempeh",
    "meat": "tofurky deli slice",
    "beef": "tofurky deli slice",
    "veal": "tofurky deli slice",
    "lamb": "tofurky deli slice",
    "tuna": "tempeh",
    "tilapia": "tempeh",
    "sardine": "tempeh",
    "salmon": "tempeh",
    "squid": "tempeh",
    "cod": "tempeh",
    "clam": "tempeh",
    "halibut": "tempeh",
    "anchovy": "tempeh",
    "anchovie": "tempeh",
    "mackerel": "tempeh",
    "calamari": "tempeh",
    "shrimp": "tofu",
    "prawn": "tofu",
    "gelatin": "agar flakes"
}

to_vegan_list = {
    "chicken bouillon": "vegetable bouillon",
    "beef bouillon": "vegetable bouillon",
    "pork bouillon": "vegetable bouillon",
    "chicken broth": "vegetable broth",
    "beef broth": "vegetable broth",
    "chicken stock": "vegetable broth",
    "beef stock": "vegetable broth",
    "pork stock": "vegetable broth",
    "chicken": "tofu",
    "meat": "tofu",
    "beef": "tempeh",
    "veal": "tofu",
    "lamb": "tempeh",
    "bacon": "vegan bacon",
    "steak": "seitan steak",
    "turkey": "tofurky",
    "pepperoni": "tofurky deli slice",
    "pastrami": "tofurky deli slice",
    "salami": "tofurky deli slice",
    "ribs": "seitan ribs",
    "ground meat": "textured soy protein",
    "ground beef": "textured soy protein",
    "ground pork": "textured soy protein",
    "filet mignon": "portobello mushroom",
    "rib-eye": "portobello mushroom",
    "burger": "veggie burger",
    "meatball": "veggie meatball",
    "sausage": "veggie sausage",
    "chicken breast": "seitan tenders",
    "chicken thigh": "seitan tenders",
    "chicken leg": "seitan tenders",
    "chicken nuggets": "seitan nuggets",
    "pork": "tempeh",
    "jerky": "veggie jerky",
    "tuna": "tempeh",
    "tilapia": "tempeh",
    "sardine": "tempeh",
    "salmon": "tempeh",
    "squid": "tempeh",
    "cod": "tempeh",
    "clam": "tempeh",
    "halibut": "tempeh",
    "anchovy": "tempeh",
    "anchovie": "tempeh",
    "calamari": "tempeh",
    "shrimp": "tofu",
    "prawn": "tofu",
    "milk": "soy milk",
    "milk powder": "almond milk powder",
    "ice cream": "soy ice cream",
    "mozzarella cheese": "vegan mozzarella cheese",
    "mozzarella": "vegan mozzarella",
    "parmesan cheese": "vegan parmesan cheese",
    "cheese": "crumbled tofu",
    "butter": "vegan margarine",
    "yogurt": "almond milk yogurt",
    "scrambled egg": "tofu scramble",
    "egg yolk": "tofu",
    "egg": "tofu",
    "yolk": "tofu",
    "instant pudding": "dairy free instant pudding",
    "pudding": "dairy free pudding",
    "sour cream": "vegan sour cream",
    "mayonnaise": "vegan mayonnaise",
    "ketchup": "vegan ketchup",
    "gelatin": "agar flakes",
    "honey": "agave nectar",
    "chocolate": "non-dairy chocolate",
    "hollandaise sauce": "vegan hollandaise sauce",
    "oyster sauce": "vegetarian oyster sauce",
    "worcestershire sauce": "organic worcestershire sauce",
    "bread": "wheat tortilla",
    "bread toasts": "wheat tortilla",
    "bagel": "vegan bagel",
    "pancake": "vegan pancake"
}
