from_vegan_to_nonveg= {
"vegetable broth": "beef broth",
"textured soy protein": "ground meat",
"portobello mushroom": "steak",
"vegetable oil": "nut butter",
"canola oil": "nut butter",
"olive oil": "nut butter",
"peanut oil": "butter",
"coconut oil" : "butter",
"corn oil": "butter",
"sunflower oil" : "nut butter",
"safflower oil" : "butter",
"almond oil" : "butter",
"almond milk" : "milk",
"coconut milk" : "milk",
"soy milk" : "milk",
"cashew milk" : "milk",
"rice milk" : "milk",
"oat milk" : "milk",
"eggplant" : "chicken",
"soy patties" : "chicken",
"soy nuggets" : "chicken nuggets",
"veggie jerky" : "jerky",
"tempeh" : "pork",
"soy ice cream" : "milk ice cream",
"rice ice cream": "milk ice cream",
"crumbled tofu" :  "cheese",
"soaked raw nuts" : "cheese",
"agar flakes" : "gelatin",
"liquid sweetener" : "honey",
"soy yogurt" : "Greek yogurt",
"coconut yogurt" : "Greek yogurt",
"almond yogurt" : "yogurt",
"pureed soft tofu" : "beaten egg",
"mashed bananas" : "beaten egg",
"ground beef" : "textured soy protein",
"ground pork" : "textured soy protein",
"pepperoni" : "veggie deli slice",
"pastrami" : "veggie deli slice",
"salami" : "veggie deli slice",
"steak" : "portobello mushroom",
"filet mignon" : "portobello mushroom",
"rib-eye" : "portobello mushroom",
"ribs" : "portobello mushroom",
"burger" : "veggie burger",
"meatball" : "veggie meatball",
"sausage" : "veggie sausage",
"bacon": "veggie bacon" }
    
normal_to_chinese= {
"olive oil" : "peanut oil",
"spaghetti" : "lo mein",
"vinegar" : "black vinegar",
"red pepper flakes" : "dried chili pepper",
"italian parsley" : "cilantro",
"parmigiano-reggiano cheese" : "fermented bean curd",
"penne" : "lo mein",
"mushrooms" : "shiitake mushrooms",
"salad" : "Malatang",
"Quesadilla" : "Xian Bing",
"Burger" : "Chinese Hamburger",
"French pancake" : "Jian Bing",
"Meat Sauce" : "Da Lu Mian",
"Churro" : "You Tiao",
"Pizza" : "Scallion Pancake",
"wine" :"shaojiu",
"pork" : "tofu",
"chicken nuggets" : "chicken balls",
"jerky" : "Bak Kwa",
"pork" : "Mapo Doufu",
"meat" : "Bakkwa",
"lamb" : "lamb broth",
}